version: '3.8'
services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack-sqs
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./localstack/ready.d:/etc/localstack/init/ready.d"  # scripts executed when LS is ready
