package com.sqs.sqsproject.employee;

import com.sqs.sqsproject.jdbc.JdbcBulkUpsertUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

@Repository
@RequiredArgsConstructor
public class EmployeeJdbcRepository {

    private final JdbcTemplate jdbcTemplate;

    /**
     * Performs bulk upsert (insert/update) by unique email using JDBC batchUpdate for efficiency.
     * Uses Postgres ON CONFLICT for idempotency. Returns per-row update counts from the last batch.
     */
    public int[] bulkUpsert(List<Employee> employees) {
        if (employees == null || employees.isEmpty()) return new int[0];

        // Filter invalid rows according to NOT NULL constraints in schema
        List<Employee> valid = new ArrayList<>();
        for (Employee e : employees) {
            if (e == null) continue;
            if (e.getEmail() == null || e.getFirstName() == null || e.getLastName() == null) continue;
            valid.add(e);
        }
        if (valid.isEmpty()) return new int[0];

        // Delegate to generic bulk upsert utility
        List<String> columns = Arrays.asList("id", "first_name", "last_name", "email", "department", "hired_at");
        List<String> valueExpressions = Arrays.asList(
                "nextval('employees_id_seq')", // id generated by sequence
                "?", // first_name
                "?", // last_name
                "?", // email
                "?", // department
                "?"  // hired_at
        );
        List<String> conflictColumns = Arrays.asList("email");
        List<String> updateColumns = Arrays.asList("first_name", "last_name", "department", "hired_at");

        return JdbcBulkUpsertUtil.bulkUpsert(
                jdbcTemplate,
                valid,
                "employees",
                columns,
                valueExpressions,
                conflictColumns,
                updateColumns,
                (ps, e) -> {
                    // Bind placeholders in the exact order of "?" in valueExpressions
                    ps.setString(1, e.getFirstName());
                    ps.setString(2, e.getLastName());
                    ps.setString(3, e.getEmail());
                    if (e.getDepartment() != null) {
                        ps.setString(4, e.getDepartment());
                    } else {
                        ps.setNull(4, java.sql.Types.VARCHAR);
                    }
                    Instant hiredAt = e.getHiredAt();
                    if (hiredAt != null) {
                        ps.setTimestamp(5, Timestamp.from(hiredAt));
                    } else {
                        ps.setNull(5, java.sql.Types.TIMESTAMP);
                    }
                },
                1000
        );
    }
}
